# Generated by Django 5.2.4 on 2025-07-05 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres del Deudor')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos del Deudor')),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
                ('operacion', models.CharField(blank=True, max_length=100, verbose_name='Operación')),
                ('etapa_juicio', models.CharField(choices=[('LANZAMIENTO', 'Lanzamiento'), ('RECUPERADA', 'Vivienda recuperada')], max_length=50, verbose_name='Etapa del Juicio')),
                ('total_costas', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total Costas')),
                ('estado_causa', models.CharField(choices=[('RECUPERADO', 'Recuperado'), ('ACTIVO', 'Activo')], max_length=50, verbose_name='Estado de la Causa')),
                ('arbitro', models.CharField(blank=True, max_length=200, verbose_name='Árbitro')),
                ('fecha_asignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('abogado_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Abogado Encargado')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.deudor', verbose_name='Deudor Asociado')),
                ('tribunal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='causas.tribunal', verbose_name='Tribunal')),
            ],
        ),
    ]
