# Generated by Django 5.2.4 on 2025-07-06 17:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='causa',
            options={'ordering': ['-ultima_actualizacion']},
        ),
        migrations.AddField(
            model_name='causa',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 6, 17, 55, 0, 813920, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Ingreso al Sistema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='causa',
            name='ultima_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='estado_causa',
            field=models.CharField(choices=[('RECUPERADO', 'Recuperado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('ARCHIVADO', 'Archivado')], max_length=50, verbose_name='Estado de la Causa'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='etapa_juicio',
            field=models.CharField(choices=[('LANZAMIENTO', 'Lanzamiento'), ('VIVIENDA_RECUPERADA', 'Vivienda recuperada'), ('CANCELACION_CBR', 'Cancelación en CBR'), ('OTRA', 'Otra')], max_length=50, verbose_name='Etapa del Juicio'),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='rut',
            field=models.CharField(help_text='RUT sin puntos y con guión', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='causa',
            name='cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='causas.cartera', verbose_name='Cartera de Cliente'),
        ),
    ]
