# Generated by Django 5.2.4 on 2025-07-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0002_cartera_alter_causa_options_causa_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_asociada', models.CharField(choices=[('LANZAMIENTO', 'Lanzamiento'), ('VIVIENDA_RECUPERADA', 'Vivienda recuperada'), ('CANCELACION_CBR', 'Cancelación en CBR'), ('OTRA', 'Otra')], max_length=50, verbose_name='Etapa Asociada')),
                ('archivo', models.FileField(upload_to='adjuntos_causas/', verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción del Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='causas.causa')),
            ],
        ),
    ]
