# Generated by Django 5.2.4 on 2025-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='demandante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Demandante'),
        ),
        migrations.AddField(
            model_name='causa',
            name='fecha_estado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estado'),
        ),
        migrations.AddField(
            model_name='causa',
            name='mes_ano_cuota_morosa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mes y Año Cuota Morosa'),
        ),
        migrations.AddField(
            model_name='causa',
            name='n_dividendo_moroso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Dividendo Moroso'),
        ),
        migrations.AddField(
            model_name='causa',
            name='rol_exhorto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rol Exhorto'),
        ),
        migrations.AddField(
            model_name='causa',
            name='rol_juez_arbitro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rol Juez Árbitro'),
        ),
        migrations.AddField(
            model_name='causa',
            name='tribunal_exhorto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tribunal Exhorto'),
        ),
        migrations.AddField(
            model_name='causa',
            name='ubicacion_expediente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación Expediente'),
        ),
        migrations.AddField(
            model_name='deudor',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='deudor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
    ]
