# Generated by Django 5.2.4 on 2025-07-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0005_causa_demandante_causa_fecha_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesLeasing',
            fields=[
                ('causa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='causas.causa')),
                ('repertorio', models.CharField(blank=True, max_length=100)),
                ('nombre_notaria', models.CharField(blank=True, max_length=200, verbose_name='Nombre Notaría')),
                ('comuna_notaria', models.CharField(blank=True, max_length=100, verbose_name='Comuna Notaría')),
                ('fecha_escritura', models.DateField(blank=True, null=True, verbose_name='Fecha Escritura')),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('precio_compraventa_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Compraventa UF')),
                ('aporte_mensual_uf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Aporte Mensual UF')),
                ('fecha_primera_cuota', models.CharField(blank=True, max_length=100, verbose_name='Fecha Primera Cuota')),
                ('plazo_arriendo', models.IntegerField(blank=True, null=True, verbose_name='Plazo Arriendo (meses)')),
                ('clausula_penal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cláusula Penal')),
                ('ubicacion_clausula_penal', models.CharField(blank=True, max_length=200, verbose_name='Ubicación Cláusula Penal')),
            ],
        ),
    ]
