# Generated by Django 5.2.4 on 2025-07-23 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0006_antecedentesleasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesCBR',
            fields=[
                ('causa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='causas.causa')),
                ('direccion_vivienda_cbr', models.TextField(blank=True, verbose_name='Dirección Vivienda CBR')),
                ('comuna_cbr', models.CharField(blank=True, max_length=100, verbose_name='Comuna CBR')),
                ('fojas_dominio', models.CharField(blank=True, max_length=100, verbose_name='Fojas Dominio')),
                ('numero_dominio', models.CharField(blank=True, max_length=100, verbose_name='Número Dominio')),
                ('ano_dominio', models.CharField(blank=True, max_length=4, verbose_name='Año Dominio')),
                ('fojas_arriendo', models.CharField(blank=True, max_length=100, verbose_name='Fojas Arriendo')),
                ('numero_arriendo', models.CharField(blank=True, max_length=100, verbose_name='Número Arriendo')),
                ('ano_arriendo', models.CharField(blank=True, max_length=4, verbose_name='Año Arriendo')),
                ('repertorio_cesion', models.CharField(blank=True, max_length=100, verbose_name='Repertorio Cesión')),
                ('nombre_notaria_cesion', models.CharField(blank=True, max_length=200, verbose_name='Nombre Notaría Cesión')),
                ('comuna_notaria_cesion', models.CharField(blank=True, max_length=100, verbose_name='Comuna Notaría Cesión')),
                ('fecha_escritura_cesion', models.DateField(blank=True, null=True, verbose_name='Fecha Escritura Cesión')),
            ],
        ),
    ]
