# Generated by Django 5.2.4 on 2025-07-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0007_antecedentescbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('notificacion', models.TextField(blank=True, verbose_name='Notificación')),
                ('fecha_accion', models.DateField(verbose_name='Fecha Acción')),
                ('escritos', models.TextField(blank=True, verbose_name='Escritos')),
                ('costas', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='causas.causa')),
            ],
            options={
                'ordering': ['-fecha_accion', '-fecha_creacion'],
            },
        ),
    ]
