# Generated by Django 5.2.4 on 2025-07-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0008_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='etapa_juicio',
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='etapa_asociada',
            field=models.CharField(choices=[('LANZAMIENTO', 'Lanzamiento'), ('RESOLUCION', 'Resolución'), ('SENTENCIA', 'Sentencia'), ('OTRA', 'Otra')], max_length=50, verbose_name='Etapa Asociada'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='arbitro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Juez Árbitro'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='rol',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rol Civil'),
        ),
        migrations.CreateModel(
            name='EtapaJuicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_etapa', models.CharField(choices=[('LANZAMIENTO', 'Lanzamiento'), ('RESOLUCION', 'Resolución'), ('SENTENCIA', 'Sentencia'), ('OTRA', 'Otra')], max_length=50, verbose_name='Tipo de Etapa')),
                ('fecha_etapa', models.DateField(verbose_name='Fecha de la Etapa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Notificación')),
                ('costas', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.causa')),
            ],
            options={
                'ordering': ['-fecha_etapa', '-fecha_creacion'],
            },
        ),
    ]
