# Generated by Django 5.2.4 on 2025-07-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0009_remove_causa_etapa_juicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='etapajuicio',
            name='causa',
        ),
        migrations.AlterModelOptions(
            name='causa',
            options={},
        ),
        migrations.RemoveField(
            model_name='archivoadjunto',
            name='causa',
        ),
        migrations.RemoveField(
            model_name='archivoadjunto',
            name='etapa_asociada',
        ),
        migrations.RemoveField(
            model_name='archivoadjunto',
            name='fecha_subida',
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='adjuntos_causas/'),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='EtapaCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('costas', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='causas.causa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='causas.etapa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='etapa_causa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='causas.etapacausa'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tipo_etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.tipoetapa'),
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
        migrations.DeleteModel(
            name='EtapaJuicio',
        ),
    ]
